/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerWorkoutsRouteImport } from './routes/trainer/workouts'
import { Route as TrainerProgressRouteImport } from './routes/trainer/progress'
import { Route as TrainerFilesRouteImport } from './routes/trainer/files'
import { Route as TrainerDietsRouteImport } from './routes/trainer/diets'
import { Route as TrainerDashboardRouteImport } from './routes/trainer/dashboard'
import { Route as TrainerClientsRouteImport } from './routes/trainer/clients'
import { Route as ClientWorkoutsRouteImport } from './routes/client/workouts'
import { Route as ClientProgressRouteImport } from './routes/client/progress'
import { Route as ClientFilesRouteImport } from './routes/client/files'
import { Route as ClientDietsRouteImport } from './routes/client/diets'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LoginCoachRouteRouteImport } from './routes/login_/coach/route'
import { Route as LoginClientRouteRouteImport } from './routes/login_/client/route'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerWorkoutsRoute = TrainerWorkoutsRouteImport.update({
  id: '/trainer/workouts',
  path: '/trainer/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerProgressRoute = TrainerProgressRouteImport.update({
  id: '/trainer/progress',
  path: '/trainer/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerFilesRoute = TrainerFilesRouteImport.update({
  id: '/trainer/files',
  path: '/trainer/files',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerDietsRoute = TrainerDietsRouteImport.update({
  id: '/trainer/diets',
  path: '/trainer/diets',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerDashboardRoute = TrainerDashboardRouteImport.update({
  id: '/trainer/dashboard',
  path: '/trainer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerClientsRoute = TrainerClientsRouteImport.update({
  id: '/trainer/clients',
  path: '/trainer/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientWorkoutsRoute = ClientWorkoutsRouteImport.update({
  id: '/client/workouts',
  path: '/client/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProgressRoute = ClientProgressRouteImport.update({
  id: '/client/progress',
  path: '/client/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientFilesRoute = ClientFilesRouteImport.update({
  id: '/client/files',
  path: '/client/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDietsRoute = ClientDietsRouteImport.update({
  id: '/client/diets',
  path: '/client/diets',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCoachRouteRoute = LoginCoachRouteRouteImport.update({
  id: '/login_/coach',
  path: '/login/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginClientRouteRoute = LoginClientRouteRouteImport.update({
  id: '/login_/client',
  path: '/login/client',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/login/client': typeof LoginClientRouteRoute
  '/login/coach': typeof LoginCoachRouteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/diets': typeof ClientDietsRoute
  '/client/files': typeof ClientFilesRoute
  '/client/progress': typeof ClientProgressRoute
  '/client/workouts': typeof ClientWorkoutsRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/trainer/diets': typeof TrainerDietsRoute
  '/trainer/files': typeof TrainerFilesRoute
  '/trainer/progress': typeof TrainerProgressRoute
  '/trainer/workouts': typeof TrainerWorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/login/client': typeof LoginClientRouteRoute
  '/login/coach': typeof LoginCoachRouteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/diets': typeof ClientDietsRoute
  '/client/files': typeof ClientFilesRoute
  '/client/progress': typeof ClientProgressRoute
  '/client/workouts': typeof ClientWorkoutsRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/trainer/diets': typeof TrainerDietsRoute
  '/trainer/files': typeof TrainerFilesRoute
  '/trainer/progress': typeof TrainerProgressRoute
  '/trainer/workouts': typeof TrainerWorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/login_/client': typeof LoginClientRouteRoute
  '/login_/coach': typeof LoginCoachRouteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/diets': typeof ClientDietsRoute
  '/client/files': typeof ClientFilesRoute
  '/client/progress': typeof ClientProgressRoute
  '/client/workouts': typeof ClientWorkoutsRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/trainer/diets': typeof TrainerDietsRoute
  '/trainer/files': typeof TrainerFilesRoute
  '/trainer/progress': typeof TrainerProgressRoute
  '/trainer/workouts': typeof TrainerWorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/login/client'
    | '/login/coach'
    | '/auth/callback'
    | '/client/dashboard'
    | '/client/diets'
    | '/client/files'
    | '/client/progress'
    | '/client/workouts'
    | '/trainer/clients'
    | '/trainer/dashboard'
    | '/trainer/diets'
    | '/trainer/files'
    | '/trainer/progress'
    | '/trainer/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/login/client'
    | '/login/coach'
    | '/auth/callback'
    | '/client/dashboard'
    | '/client/diets'
    | '/client/files'
    | '/client/progress'
    | '/client/workouts'
    | '/trainer/clients'
    | '/trainer/dashboard'
    | '/trainer/diets'
    | '/trainer/files'
    | '/trainer/progress'
    | '/trainer/workouts'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/login_/client'
    | '/login_/coach'
    | '/auth/callback'
    | '/client/dashboard'
    | '/client/diets'
    | '/client/files'
    | '/client/progress'
    | '/client/workouts'
    | '/trainer/clients'
    | '/trainer/dashboard'
    | '/trainer/diets'
    | '/trainer/files'
    | '/trainer/progress'
    | '/trainer/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LoginClientRouteRoute: typeof LoginClientRouteRoute
  LoginCoachRouteRoute: typeof LoginCoachRouteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientDietsRoute: typeof ClientDietsRoute
  ClientFilesRoute: typeof ClientFilesRoute
  ClientProgressRoute: typeof ClientProgressRoute
  ClientWorkoutsRoute: typeof ClientWorkoutsRoute
  TrainerClientsRoute: typeof TrainerClientsRoute
  TrainerDashboardRoute: typeof TrainerDashboardRoute
  TrainerDietsRoute: typeof TrainerDietsRoute
  TrainerFilesRoute: typeof TrainerFilesRoute
  TrainerProgressRoute: typeof TrainerProgressRoute
  TrainerWorkoutsRoute: typeof TrainerWorkoutsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/workouts': {
      id: '/trainer/workouts'
      path: '/trainer/workouts'
      fullPath: '/trainer/workouts'
      preLoaderRoute: typeof TrainerWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/progress': {
      id: '/trainer/progress'
      path: '/trainer/progress'
      fullPath: '/trainer/progress'
      preLoaderRoute: typeof TrainerProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/files': {
      id: '/trainer/files'
      path: '/trainer/files'
      fullPath: '/trainer/files'
      preLoaderRoute: typeof TrainerFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/diets': {
      id: '/trainer/diets'
      path: '/trainer/diets'
      fullPath: '/trainer/diets'
      preLoaderRoute: typeof TrainerDietsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/dashboard': {
      id: '/trainer/dashboard'
      path: '/trainer/dashboard'
      fullPath: '/trainer/dashboard'
      preLoaderRoute: typeof TrainerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/clients': {
      id: '/trainer/clients'
      path: '/trainer/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof TrainerClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/workouts': {
      id: '/client/workouts'
      path: '/client/workouts'
      fullPath: '/client/workouts'
      preLoaderRoute: typeof ClientWorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/progress': {
      id: '/client/progress'
      path: '/client/progress'
      fullPath: '/client/progress'
      preLoaderRoute: typeof ClientProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/files': {
      id: '/client/files'
      path: '/client/files'
      fullPath: '/client/files'
      preLoaderRoute: typeof ClientFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/diets': {
      id: '/client/diets'
      path: '/client/diets'
      fullPath: '/client/diets'
      preLoaderRoute: typeof ClientDietsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/coach': {
      id: '/login_/coach'
      path: '/login/coach'
      fullPath: '/login/coach'
      preLoaderRoute: typeof LoginCoachRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/client': {
      id: '/login_/client'
      path: '/login/client'
      fullPath: '/login/client'
      preLoaderRoute: typeof LoginClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LoginClientRouteRoute: LoginClientRouteRoute,
  LoginCoachRouteRoute: LoginCoachRouteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientDietsRoute: ClientDietsRoute,
  ClientFilesRoute: ClientFilesRoute,
  ClientProgressRoute: ClientProgressRoute,
  ClientWorkoutsRoute: ClientWorkoutsRoute,
  TrainerClientsRoute: TrainerClientsRoute,
  TrainerDashboardRoute: TrainerDashboardRoute,
  TrainerDietsRoute: TrainerDietsRoute,
  TrainerFilesRoute: TrainerFilesRoute,
  TrainerProgressRoute: TrainerProgressRoute,
  TrainerWorkoutsRoute: TrainerWorkoutsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
